from selenium import webdriver
import time

PATH = "C:\Program Files (x86)\webdriver\chromedriver.exe"
driver = webdriver.Chrome(PATH)
action = webdriver.ActionChains(driver)
driver.get("https://www.ebay.com/")
driver.maximize_window()
time.sleep(5)
element = driver.find_element_by_link_text ("Electronics")
action.move_to_element(element)
action.perform()
link = driver.find_element_by_xpath ("//a[contains(text(),'Cell phones and accessories')]")
link.click()
link = driver.find_element_by_xpath ("//a[contains(text(),'Cell Phones & Smartphones')]")
link.click()
link = driver.find_element_by_xpath ("//button[contains(text(),'All Filters')]")
link.click()
time.sleep(10)
link = driver.find_element_by_xpath ("/html/body/div[14]/div[2]/div/form/div[1]/div[1]/div/div[7]")
link.click()
time.sleep(5)
link = driver.find_element_by_xpath ("/html/body/div[14]/div[2]/div/form/div[1]/div[2]/div[1]/div/fieldset/div[1]/div[3]/label/input")
link.click()
time.sleep(5)
link = driver.find_element_by_xpath ("/html/body/div[14]/div[2]/div/form/div[1]/div[1]/div/div[23]")
link.click()
time.sleep(5)
link = driver.find_element_by_xpath ("/html/body/div[14]/div[2]/div/form/div[1]/div[2]/div[1]/div/fieldset/ul/li/div[2]/div/div[1]/div/input")
link.click()
time.sleep(5)
link = driver.find_element_by_xpath ("/html/body/div[14]/div[2]/div/form/div[1]/div[2]/div[1]/div/fieldset/ul/li/div[2]/div/div[1]/div/input")
link.send_keys("1000000")
link = driver.find_element_by_xpath ("/html/body/div[14]/div[2]/div/form/div[1]/div[2]/div[1]/div/fieldset/ul/li/div[2]/div/div[2]/div/input")
link.send_keys('2000000')
time.sleep(5)
link = driver.find_element_by_xpath ("/html/body/div[14]/div[2]/div/form/div[1]/div[1]/div/div[25]")
link.click()
time.sleep(5)
link = driver.find_element_by_xpath ("/html/body/div[14]/div[2]/div/form/div[1]/div[2]/div[1]/div/fieldset/div[5]/label/input")
link.click()
time.sleep(3)
link = driver.find_element_by_xpath ("/html/body/div[14]/div[2]/div/form/div[3]/div[2]/button")
link.click()
time.sleep(5)